### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by DarkPanther232** [Plagiatus/datapacks#1]
I tried doing multiple things including following  Xisumavoid's video and just putting the zip file in my datapack folder for my server and nothing is working is it just me or is there something wrong with it for 1.13?

**Comment by Plagiatus** [comment]
Which Datapack are you referring to? (there are two datapacks in this repository)

What exactly isn't working?

Please be as specific as you can, otherwise I won't be able to assist you.

**Comment by SteveKunG** [comment]
(Multiplayer Sleep)
Probably this is same issue with Realms Server. I tried to put zip and upload into Realms it doesn't work.

**Comment by Plagiatus** [comment]
> Probably this is same issue with Realms Server

most definitly, yes. realms are basically vanilla servers, so if it doesn't work on a vanilla server it won't work on realms.  
but also for you: I'll need more information on how to recreate the problem, because for me what I tried is working just fine.

**Comment by SteveKunG** [comment]
I just drop datapack zip into it folder. Datapack show in game, including function.

**Comment by Plagiatus** [comment]
Well then it should work fine?

What exactly isn't working? Just nothing at all?
What is happening if you run

    scoreboard objectives setdisplay sidebar multSleep.count

And what if you sleep in a bed with that open?

**Comment by SteveKunG** [comment]
Nothing happened.
Edit: OK, I try run function `multiplayer_sleep:start` and I got it working!

![2018-08-13_05 39 44](https://user-images.githubusercontent.com/6128413/44007191-4a993098-9ebb-11e8-8473-f65da36704bb.png)

**Comment by Plagiatus** [comment]
That is weird indeed. Are there any errors in the logs when you do /reload?  
Are you able to run the functions or grant the advancements manually via commands?
