### ISSUE TITLE
PreloadWorld doesn't let me set the area

### ISSUE THREAD

**Issue by hgjrnjghnjgh** [Plagiatus/datapacks#14]
I'm attempting to pregen a world to 8k out blocks in any given direction, I ran it once to test it and it runs fine, I reset the Overworld and Nether "Dimension" to 1 so that it would run them again, and then changed "Width" to 16384, ran it again and it ran the same 1028 block area it had with default, I don't know if I'm changing the wrong setting or if it simply isn't working, but I'd appreciate any help

**Comment by Plagiatus** [comment]
Please read the part about Width again:

> #### Width
> _Default: 1024_  
> To set the size of your pre-generated area, use `DX` and `DZ`. These describe the side length of the generated area, centered around `X` and `Z` _(not around worldspawn!)_. This means that the default value of 1024 will pre-generate the area from `-512 ~ -512` to `+512 ~ +512` (assuming `X` and `Z` are set to their default of 0). These values are independant of each other.  
> Be aware that the generated area is _at least_ the size given in `DX` and `DZ`, and will most likely be a little bit bigger depending on many factors.

It says "use `DX` and `DZ`", so changing `Width` won't do anything at all.

**Comment by hgjrnjghnjgh** [comment]
I did try that once, but I guess I did something wrong, it works now! Thank you :D
