### ISSUE TITLE
i don't now how/where too dowload the homes datapack

### ISSUE THREAD

**Issue by slimmejeff** [Plagiatus/datapacks#15]

**Comment by Plagiatus** [comment]
Not sure how you made it to the issues without finding the download link! 😄

Beautiful page: https://plagiatus.github.io/datapacks/

Less beautiful page: https://github.com/Plagiatus/datapacks/tree/master/homes

Direct link: https://github.com/Plagiatus/datapacks/raw/master/homes/homes_v1.2.zip
