### ISSUE TITLE
Multisleep Error

### ISSUE THREAD

**Issue by xombiemike** [Plagiatus/datapacks#3]
I'm on a vinalla MC 1.13 using multisleep. It works most of the time, but occasionally I'll get kicked from the server with a message that flying is not enabled on the server. When I log back in it seems to work on the next try.

**Comment by Plagiatus** [comment]
this sounds like a minecraft bug as I'm not changing or messing with the player in any way.

you can try to turn flying on in the server.properties, that may avoid you being kicked.
