### ISSUE TITLE
Rain after a player has slept

### ISSUE THREAD

**Issue by matcool** [Plagiatus/datapacks#5]
I have tested this for 3 consecutive nights and every time a player sleeps it starts to rain right after they are up.
My server is currently running spigot 1.13.1

**Comment by Plagiatus** [comment]
1) you're not using my version but Xisumas version, correct?

2) do you happen to have set your doWeatherCycle gamerule to false?

If these are true, open up the skip.mcfunction file and remove the `weather` line from the top.
