### ISSUE TITLE
mobs don't drop raw meat

### ISSUE THREAD

**Issue by sheeeev66** [Plagiatus/datapacks#7]
I uploaded the data pack on my server the other day and when I killed a sheep to make a bed the sheep dropped cooked mutton despite the fact my sword wasn't enchanted.
I downloaded the data pack today on my testing world and I realized that whenever I kill an animal it drops his meat cooked no matter what tool I used or if I used my fist to kill the animal.
pleas can you help me fix this.
thank you for your time and patience.

**Comment by Plagiatus** [comment]
I uhhh... Am not sure what datapack you're referring to, because I don't think I have any datapacks that alter the drops of animals. Can you please clarify which datapack you're talking about?

**Comment by sheeeev66** [comment]
I'm using the headdrops data pack  and the latest version

**Comment by Plagiatus** [comment]
I cannot reproduce this issue. in my testworld the mobs drop their normal drops. can you send me a world where this is an issue?

**Comment by sheeeev66** [comment]
[2019-06-07_22-25-45_test for bug.zip](https://github.com/Plagiatus/datapacks/files/3267315/2019-06-07_22-25-45_test.for.bug.zip)
it seems that the bug occurs only when it's with these two datapacks but when they are alone the bug doesn't happen

**Comment by sheeeev66** [comment]
it seems that the issue is with another datapack.
sorry for your time
