### ISSUE TITLE
Multiplayer sleep makes it never rain - alternative fix

### ISSUE THREAD

**Issue by A-Smith** [Plagiatus/datapacks#9]
The multiplayer sleep effectively makes it so rain never happens, because it sets "weather clear 999999" whenever someone sleeps. Removing the statement (as suggested in a previous issue) means sleeping does not clear rain, which is not ideal. On my server, I have changed this to "weather rain 1". The one second of rain is barely noticeable, and after the second of rain stop, Minecraft is back to it's "normal" rain cycle.

**Comment by Plagiatus** [comment]
Thank you for your suggestion. This is already noted on the download page under [Further information](https://github.com/Plagiatus/datapacks/blob/master/multiplayer_sleep/README.md#further-information), point 3. It includes a download to a file that does exactly what you suggested.
